<?php

namespace App\Repositories;

use App\Entities;

/**
 * OrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderRepository extends \Doctrine\ORM\EntityRepository
{
    use \LaravelDoctrine\ORM\Pagination\PaginatesFromRequest;

    function lastest($perPage = 5, $pageName= "page") 
    {
        $builder = $this->createQueryBuilder('o');
        $builder->orderBy('o.date' , 'DESC');

        return $this->paginate($builder->getQuery(), $perPage, $pageName);
    }

    /**
     * @param Entity\Area $area
     */
    function fromArea(Entities\Area $area, $perPage = 5, $pageName= "page") 
    {
        $builder = $this->createQueryBuilder('o');
        $builder->where("o.area = {$area->getId()}");
        $builder->orderBy('o.date' , 'DESC');

        return $this->paginate($builder->getQuery(), $perPage, $pageName);
    }

    /**
     * @param Entity\Supplier $supplier
     */
    function fromSupplier(Entities\Supplier $supplier, $perPage = 5, $pageName= "page") 
    {
        $builder = $this->createQueryBuilder('o');
        $builder->innerJoin('o.products', 'p')
                ->innerJoin('p.supplier', 's')
                ->andWhere('s.id = :id')
                ->orderBy('o.created' , 'DESC')
                ->setParameters([
                    'id' => $supplier
                ]);

        return $this->paginate($builder->getQuery(), $perPage, $pageName);
    }

    /**
     *
     */
    function search(
        $sequence = null, 
        $from = null, 
        $to = null, 
        $area = null, 
        $type = null, 
        $status = null, 
        $perPage = 5, 
        $pageName= "page")
    {
        $builder = $this->createQueryBuilder('o');
        if ($sequence !== null) {
            $builder->andWhere("o.sequence LIKE :sequence")
                    ->setParameter('sequence', "%{$sequence}%");
        }
        if ($from !== null) {
            $builder->andWhere("o.date >= :from")
                ->setParameter('from', $from);
        }
        if ($to !== null) {
            $builder->andWhere("o.date <= :to")
                ->setParameter('to', $to);
        }
        if ($area !== null) {
            $builder->andWhere("o.area = :area")
                ->setParameter('area', $area);
        }
        if ($type !== null) {
            $builder->innerJoin('o.area', 'a')
                    ->andWhere("a.type = :type")
                    ->setParameter('type', $type);
        }
        if ($status !== null) {
            $builder->andWhere("o.status = :status")
                ->setParameter('status', $status);
        }
        $builder->orderBy('o.date' , 'DESC');

        return $this->paginate($builder->getQuery(), $perPage, $pageName);
    }
}
