<?php

namespace App\Repositories;

/**
 * OrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderRepository extends \Doctrine\ORM\EntityRepository
{
    use \LaravelDoctrine\ORM\Pagination\PaginatesFromRequest;

    function lastest($perPage = 5, $pageName= "page") 
    {
        $builder = $this->createQueryBuilder('o');
        $builder->orderBy('o.created' , 'DESC');

        return $this->paginate($builder->getQuery(), $perPage, $pageName);
    }

    function fromArea(\App\Entities\Area $area, $perPage = 5, $pageName= "page") 
    {
        $builder = $this->createQueryBuilder('o');
        $builder->where("o.area = {$area->getId()}");
        $builder->orderBy('o.created' , 'DESC');

        return $this->paginate($builder->getQuery(), $perPage, $pageName);
    }
}
