<?php

namespace App\Repositories;

/**
 * SupplierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplierRepository extends \Doctrine\ORM\EntityRepository
{
    use \LaravelDoctrine\ORM\Pagination\PaginatesFromRequest;

    function lastest($perPage = 5, $pageName= "page") 
    {
        $builder = $this->createQueryBuilder('o');
        $builder->orderBy('o.created' , 'DESC');

        return $this->paginate($builder->getQuery(), $perPage, $pageName);
    }
}
